export default {
  L1: {
    TOC: ['TABLE OF CONTENTS', 'TOC', 'DOC-TOC', 'CONTENTS', 'DOC-PAGELIST'],
    CHAPTER: ['BODYMATTER', 'CHAPTER', 'PART', 'VOLUME'],
    CONCLUSION: ['CONCLUSION', 'EPILOGUE', 'FINAL', 'LAST', 'SUMMARY'],
    INTRODUCTION: [
      'AUTHORSNOTE',
      'EPIGRAPH',
      'INTRODUCTION',
      'FRONTMATTER',
      'OPEN',
      'PREAMBLE',
      'PREFACE',
      'PROLOGUE',
      'STORY',
    ],
    USELESS: [
      'ABOUT',
      'ACKNOWLEDGMENT',
      'AUTHOR',
      'BIBLIOGRAPHY',
      'CONTRIBUTOR',
      'COPYRIGHT',
      'COVER',
      'LICENSE',
      'DEDICATION',
      'FRONTMATTER',
      'ENDNOTE',
      'EXAMPLE',
      'GLOSSARY',
      'NEWSLETTER',
      'PAGELIST',
      'QNA',
      'TABLE',
      'TITLEPAGE',
      'VIDEO',
    ],
  },
  L2: {
    TOC: ['TABLE_OF_CONTENTS', 'TABLE OF CONTENTS'],
    CHAPTER: ['PART', 'CHAPTER', 'VOLUME'],
    CONCLUSION: [
      'AFTERWORD',
      'CLOSING-REMARK',
      'CONCLU',
      'CONCLUSION',
      'EPILOGUE',
      'FINAL-THOUGHT',
      'LAST-WORD',
      'SUMMARY',
    ],
    INTRODUCTION: [
      'AUTHORSNOTE',
      'EPIGRAPH',
      'FOREWORD',
      'INTRO',
      'INTRODUCTION',
      'FRONTMATTER',
      'OPENING-REMARK',
      'PREAMBLE',
      'PREFACE',
      'PROLOGUE',
      'STORY',
    ],
    USELESS: [
      'HOW',
      'ABOUT',
      'ACKNOWLEDGMENT',
      'APPENDIX',
      'AUDIO',
      'AUTHOR',
      'BACKMATTER',
      'BIBLIOGRAPHY',
      'CODE',
      'LICENSE',
      'COLOPHON',
      'CONTRIBUTOR',
      'COPYRIGHT-PAGE',
      'COPYRIGHT',
      'COVER',
      'DEDICATION',
      'ENDNOTE',
      'EXAMPLE',
      'FIGURE',
      'FRONTMATTER',
      'GLOSSARY',
      'INDEX',
      'NEWSLETTER',
      'PAGELIST',
      'QNA',
      'SIDEBAR',
      'TABLE',
      'TITLEPAGE',
      'VIDEO',
    ],
  },
  PATH: {
    TOC: ['TABLE_OF_CONTENTS', 'TABLE OF CONTENTS', 'CONTENTS', 'TOC'],
    CHAPTER: ['PART', 'CH', 'VOL'],
    CONCLUSION: ['CONCLU', 'EPILOGUE', 'FINAL', 'LAST', 'SUMMARY'],
    INTRODUCTION: [
      'AUTHORSNOTE',
      'EPIGRAPH',
      'INTRO',
      'OPEN',
      'PREAMBLE',
      'PREFACE',
      'PROLOGUE',
      'STORY',
    ],
    USELESS: [
      'ABOUT',
      'ACKNOWLEDGMENT',
      'APPENDIX',
      'AUTHOR',
      'BIBLI',
      'COPYRIGHT',
      'COVER',
      'DEDICATION',
      'ENDNOTE',
      'EXAMPLE',
      'LICENSE',
      'GLOSSARY',
      'NEWSLETTER',
      'PAGELIST',
      'QNA',
      'TABLE',
      'TITLEPAGE',
      'VIDEO',
    ],
  },
};
